src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java
`testBuildGetWithMultipleFilters` is a duplicate of `testBuildGetWithMultipleFilter`
=> Remove duplicate test

src/main/java/io/weaviate/client/v1/schema/Schema.java, src/main/java/io/weaviate/client/v1/schema/api/ClassExists.java, src/test/java/io/weaviate/integration/client/schema/ClientSchemaTest.java
Addresses https://github.com/weaviate/java-client/issues/175
```client.schema().exists().withClassName("clazz").run(); //returns Result<Boolean>```
=> gh-175 Adds schema class exists method

src/main/java/io/weaviate/client/v1/graphql/query/Get.java, src/main/java/io/weaviate/client/v1/graphql/query/builder/GetBuilder.java, src/test/java/io/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java, src/test/java/io/weaviate/integration/client/WeaviateTestGenerics.java, src/test/java/io/weaviate/integration/client/graphql/ClusterGraphQLTest.java, src/test/resources/docker-compose-cluster.yaml
Introduces `client.graphQL().get().withConsistencyLevel()` to set desired consistency level per query.
Example:
```java
Field name = Field.builder().name("name").build();
Field _additional = Field.builder()
.name("_additional")
.fields(new Field[]{Field.builder().name("isConsistent").build()})
.build();
Result<GraphQLResponse> result = client.graphQL().get()
.withClassName("Article").withConsistencyLevel(ConsistencyLevel.ALL)
.withFields(name, _additional)
.run();
```
=> Support GQL `Get{}` consistency level

README.md, pom.xml
For engineers running on Java 9 or above, some of the tests (like `SerializerTest`) fail.
This is because when the client receives errors from Weaviate, it attempts to deserialize into `Exception`s through the use of Gson. Gson internally uses reflection on internal variables like `Throwable#detailMessage`, which is barred due to the "strict encapsulation" module system introduced in Java 9 and above. 
The result is an illegal reflection error.
To fix this, the internal `java.lang` module was opened up so tests run as intended for contributors running Java 9 or above.
As this is the case for end users as well, a message was added to the README to let users of the library know with instructions to tweak their build tools to work around this.
=> chore: fix tests for engineers running on Java 9+

src/main/java/io/weaviate/client/v1/misc/model/InvertedIndexConfig.java, src/test/java/io/weaviate/integration/client/schema/ClientSchemaTest.java
These fields were introduced in Weaviate v1.16 but support was missing in this client. This fixes that.
=> feat: Add `indexNullState` and `indexPropertyLength` field support in `InvertedIndexConfig`

src/main/java/io/weaviate/client/Config.java, src/main/java/io/weaviate/client/base/http/builder/HttpApacheClientBuilder.java, src/test/java/io/weaviate/client/ConfigTest.java, src/test/java/io/weaviate/integration/client/proxy/ClientProxyTest.java, src/test/resources/docker-compose-proxy.yaml
Usecase is for when you would want the Java client to have a proxy but not entire JVM (so don't want to use JVM flags `http.proxyHost` and `http.proxyPort`) i.e. in Spark.
I opted for using a setter as this config will rarely be used. I've also added an integration test using `nginx-proxy`.
=> Add http proxy options

src/main/java/io/weaviate/client/Config.java, src/main/java/io/weaviate/client/base/grpc/GrpcClient.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchGrpcCreateTest.java
This PR changes how we configure `gRPC` connection in Java client.
Assuming that REST endpoint works on `localhost:8080` and gRPC endpoint works on `localhost:50051`
1. One can set the `gRPC` settings using `Config` constructor:
```
new Config("https", "localhost:8080", null, 10, false, "localhost:50051")
```
3. One can set `gRPC` settings using `setGRPCSecured` and `setGRPCHost` methods:
```
Config config = Config config = new Config("http", "localhost:8080");
config.setGRPCSecured(false);
config.setGRPCHost("localhost:50051");
```
=> Modify gRPC configuration parameters in Config class

src/main/java/io/weaviate/client/WeaviateClient.java, src/main/java/io/weaviate/client/base/grpc/GrpcClient.java, src/main/java/io/weaviate/client/v1/batch/Batch.java, src/main/java/io/weaviate/client/v1/batch/api/ObjectsBatcher.java
This PR fixes this error that started occurring in tests:
```
2023-11-14 13:17:49 5.15.0 SEVERE *~*~*~ Previous channel ManagedChannelImpl{logId=1, target=localhost:32774} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true. 
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:655)
at …
```
=> Fix gRPC channel shutdown error

src/main/java/io/weaviate/client/Config.java
The `4.4.0` made a small breaking change to the `Config` class :(. 
I'm bringing back Config's class constructor which is without the `gRPC` settings.
=> Bring back the old Config constructor that's without gRPC settings

src/main/java/io/weaviate/client/WeaviateClient.java, src/main/java/io/weaviate/client/base/util/GrpcVersionSupport.java, src/main/java/io/weaviate/client/v1/batch/Batch.java, src/main/java/io/weaviate/client/v1/batch/api/ObjectsBatcher.java, src/main/java/io/weaviate/client/v1/batch/grpc/BatchObjectConverter.java, src/test/java/io/weaviate/client/base/util/GrpcVersionSupportTest.java, src/test/java/io/weaviate/integration/client/WeaviateContainer.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchGrpcVectorBytesTest.java, src/test/resources/docker-compose-azure.yaml, src/test/resources/docker-compose-cluster.yaml, src/test/resources/docker-compose-okta-cc.yaml, src/test/resources/docker-compose-okta-users.yaml, src/test/resources/docker-compose-proxy.yaml, src/test/resources/docker-compose-test.yaml, src/test/resources/docker-compose-wcs.yaml
Starting of Weaviate `v1.22.6` version gRPC API introduced `vector_bytes` field in order to more efficiently send `vector`. This PR adds support for `vector_bytes` field.
=> Switch to vector bytes field to send vector when using gRPC

pom.xml, src/main/java/io/weaviate/client/v1/schema/model/ActivityStatus.java, src/test/java/io/weaviate/integration/client/WeaviateDockerCompose.java, src/test/java/io/weaviate/integration/client/WeaviateDockerComposeCluster.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/schema/ClientSchemaTenantOffloadingTest.java
This PR:
- adds new Tenant statuses
- adds offloading e2e test
=> Add support for tenant offloading

src/main/java/io/weaviate/client/v1/graphql/query/argument/HybridArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearAudioArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearDepthArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearImageArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearImuArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearMediaArgumentHelper.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearObjectArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearTextArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearThermalArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearVectorArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearVideoArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/Targets.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/HybridArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearAudioArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearDepthArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearImageArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearImuArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearMediaArgumentHelperTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearMediaTargetsArgument.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearObjectArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearTextArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearThermalArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearVectorArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearVideoArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/TargetsTest.java, src/test/java/io/weaviate/integration/client/WeaviateDockerCompose.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/graphql/ClientGraphQLMultiTargetSearchTest.java, src/test/java/io/weaviate/integration/client/schema/ClientSchemaTenantOffloadingTest.java
This PR adds multi target search capability to all `near<Media>` and `hybrid` arguments.
=> Add support for multi target vector search

pom.xml, src/main/java/io/weaviate/client/v1/graphql/query/argument/HybridArgument.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/HybridArgumentTest.java
Closes #303
- GraphQL query builder allows specifying `maxVectorDistance` parameter for hybrid search
- Rewrote `HybridArgumentTest.java` tests in the table-driven format
- New test case in `HybridArgumentTest.java`
=> gql: Support maxVectorDistance parameter in hybrid search

src/main/java/io/weaviate/client/v1/schema/model/DataType.java
This PR adds the missing enum for the blob data type. Using the [python](https://github.com/weaviate/weaviate-python-client/blob/bcdeb277167ad4a009084fb291012779b8d4c757/weaviate/collections/classes/config.py#L118) and [TS](https://github.com/weaviate/typescript-client/blob/d88f6d2fee1eb1f364785b10c364ded794390fca/src/collections/configure/index.ts#L36) clients as a reference.  
The blob type does not support arrays
=> data-type: Add missing blob enum

src/main/java/io/weaviate/client/v1/async/WeaviateAsyncClient.java, src/main/java/io/weaviate/client/v1/async/graphql/GraphQL.java, src/main/java/io/weaviate/client/v1/async/graphql/api/Aggregate.java, src/main/java/io/weaviate/client/v1/async/graphql/api/Explore.java, src/main/java/io/weaviate/client/v1/async/graphql/api/Get.java, src/main/java/io/weaviate/client/v1/async/graphql/api/Raw.java, src/main/java/io/weaviate/client/v1/graphql/GraphQL.java, src/test/java/io/weaviate/integration/client/async/graphql/AbstractAsyncClientTest.java, src/test/java/io/weaviate/integration/client/async/graphql/ClientGraphQLMultiTargetSearchTest.java, src/test/java/io/weaviate/integration/client/async/graphql/ClientGraphQLMultiTenancyTest.java, src/test/java/io/weaviate/integration/client/async/graphql/ClientGraphQLTest.java, src/test/java/io/weaviate/integration/client/async/graphql/ClusterGraphQLTest.java, src/test/java/io/weaviate/integration/client/graphql/AbstractClientGraphQLTest.java, src/test/java/io/weaviate/integration/client/graphql/ClientGraphQLTest.java
This MR adds the async client for `graphql`  endpoint and the test suit for it.
WIP:
=> Async Client: GraphQL package

src/main/java/io/weaviate/client/base/AsyncBaseClient.java, src/main/java/io/weaviate/client/base/AsyncBaseGraphQLClient.java, src/main/java/io/weaviate/client/base/BaseClient.java, src/main/java/io/weaviate/client/base/BaseGraphQLClient.java, src/main/java/io/weaviate/client/base/Serializer.java, src/main/java/io/weaviate/client/base/http/async/WeaviateGraphQLTypedResponseConsumer.java, src/main/java/io/weaviate/client/base/util/GroupHitDeserializer.java, src/main/java/io/weaviate/client/v1/async/graphql/api/Get.java, src/main/java/io/weaviate/client/v1/auth/nimbus/BaseAuth.java, src/main/java/io/weaviate/client/v1/graphql/model/GraphQLGetBaseObject.java, src/main/java/io/weaviate/client/v1/graphql/model/GraphQLResponse.java, src/main/java/io/weaviate/client/v1/graphql/model/GraphQLTypedResponse.java, src/main/java/io/weaviate/client/v1/graphql/query/Get.java, src/test/java/io/weaviate/client/base/SerializerTest.java, src/test/java/io/weaviate/client/v1/graphql/model/GraphQLTypedResponseTest.java, src/test/java/io/weaviate/integration/client/async/graphql/ClientGraphQLTypedTest.java, src/test/java/io/weaviate/integration/client/graphql/AbstractClientGraphQLTest.java, src/test/java/io/weaviate/integration/client/graphql/ClientGraphQLTypedTest.java, src/test/java/io/weaviate/integration/tests/graphql/ClientGraphQLTypedTestSuite.java, src/test/resources/json/graphql-group-by-response.json, src/test/resources/json/graphql-response.json
The idea is to have a better way of GraphQL response serialization.
For example we have a collection in Weaviate called `Pizza` that has 4 properties defined:
- name
- description
- bestBefore
- price
We can define a class that will automatically the GraphQL response for `Pizza` collection:
```java
@Getter
public static class Pizzas {
@SerializedName(value = "Pizza")
List<Pizza> pizzas;
@Getter
public static class Pizza extends GraphQLGetBaseObject {
String name;
String description;
String bestBefore;
Float price;
}
}
```
invocation of the `GraphQL` query would look like this:
```java
try (WeaviateAsyncClient asyncClient = client.async()) {
return asyncClient.graphQL().get()
.withClassName("Pizza")
.withFields(Field.builder().name("name").build(), …
```
=> Support for GraphQL response with custom generic classes

src/main/java/io/weaviate/client/v1/async/backup/api/BackupCanceler.java, src/main/java/io/weaviate/client/v1/async/backup/api/BackupCreateStatusGetter.java, src/main/java/io/weaviate/client/v1/async/backup/api/BackupCreator.java, src/main/java/io/weaviate/client/v1/async/backup/api/BackupRestoreStatusGetter.java, src/main/java/io/weaviate/client/v1/async/backup/api/BackupRestorer.java, src/main/java/io/weaviate/client/v1/backup/api/BackupCanceler.java, src/main/java/io/weaviate/client/v1/backup/api/BackupCreateStatusGetter.java, src/main/java/io/weaviate/client/v1/backup/api/BackupCreator.java, src/main/java/io/weaviate/client/v1/backup/api/BackupRestoreStatusGetter.java, src/main/java/io/weaviate/client/v1/backup/api/BackupRestorer.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/async/backup/ClientBackupTest.java, src/test/java/io/weaviate/integration/client/backup/ClientBackupTest.java, src/test/java/io/weaviate/integration/tests/backup/BackupTestSuite.java
This PR extends sync/async clients to accept `bucket` and `path` parameters in backup operations.
As query parameters: create status, restore status, cancel.
As request body parameters: create, restore.
New tests case in `BackupTestSuite`. It's only limitation is that it doesn't verify that the bucket was set correctly, because `bucket` is irrelevant for `"filesystem"` backend, which we use in the tests.
We do pass this parameter in all requests.
=> Support dynamic backup location

.github/workflows/create-release.yaml
[`create-release` job is failing](https://github.com/weaviate/java-client/actions/runs/13413826836) because v3 support has been discontinued and we need to migrate `actions/upload-artifact` and `actions/download-artifact` to v4.
One major change in v4 is that, with artifacts now being immutable, multiple jobs cannot write to the same artifact location (same goes for jobs parametrized by a matrix). That is not the case for us, so this should be as simple as upgrading the version.
[Migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact) for reference.
=> fix: migrate actions/upload-artifact and actions/download-artifact to v4

pom.xml, src/main/java/io/weaviate/client/base/BaseClient.java, src/main/java/io/weaviate/client/base/Serializer.java, src/main/java/io/weaviate/client/v1/async/batch/api/ObjectsBatcher.java, src/main/java/io/weaviate/client/v1/async/data/api/ObjectCreator.java, src/main/java/io/weaviate/client/v1/async/data/api/ObjectUpdater.java, src/main/java/io/weaviate/client/v1/batch/api/ObjectsBatcher.java, src/main/java/io/weaviate/client/v1/batch/grpc/BatchObjectConverter.java, src/main/java/io/weaviate/client/v1/batch/model/ObjectGetResponse.java, src/main/java/io/weaviate/client/v1/data/api/ObjectCreator.java, src/main/java/io/weaviate/client/v1/data/api/ObjectUpdater.java, src/main/java/io/weaviate/client/v1/data/api/ObjectsGetter.java, src/main/java/io/weaviate/client/v1/data/model/WeaviateObject.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearVectorArgument.java, src/main/java/io/weaviate/client/v1/grpc/GRPC.java, src/main/java/io/weaviate/client/v1/misc/model/MultiVectorConfig.java, src/main/java/io/weaviate/client/v1/misc/model/VectorIndexConfig.java, src/main/java/io/weaviate/client/v1/rbac/model/Permission.java, src/main/java/io/weaviate/client/v1/rbac/model/RbacAction.java, src/test/java/io/weaviate/client/v1/data/model/ObjectTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/HybridArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearVectorArgumentTest.java, src/test/java/io/weaviate/client/v1/grpc/GRPCTest.java, src/test/java/io/weaviate/integration/client/async/batch/ClientBatchGrpcCreateNamedVectorsTest.java, src/test/java/io/weaviate/integration/client/async/data/ClientDataTest.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchGrpcCreateNamedVectorsTest.java, src/test/java/io/weaviate/integration/client/data/ClientDataTest.java, src/test/java/io/weaviate/integration/tests/batch/ClientBatchGrpcCreateNamedVectorsTestSuite.java
This PR adds supports for ColBERT embeddings / multi-vectors.
Notable changes:
- Collection has a new parameter `MultiVectorConfig`
- GRPC util methods extended to handle `Float[][]` vectors (`byteops` package as a reference implementation) 
- Custom JsonSerializer + JsonDeserializer for `WeaviateObject` which merges named vectors and named "multi-vectors" to `"vectors"` field
Note, that WeaviateObject does not have a `Float[][] vector` field, as [Weaviate only expects 1d-vectors under `"vector"`](https://github.com/weaviate/weaviate/blob/7bcbd61a893de80a0724da31ecee4b26485c5538/entities/models/object.go#L31-L63).
- Unit tests for float arrays (de-)serialization
- Integration tests for:
- collection configuration
- creating/updating multi-vectors on a collection
- batch insertion
=> feat(ColBERT): Create, update, batch insert, and query objects with multi-vector indices 

src/main/java/io/weaviate/client/v1/async/batch/api/ObjectsBatcher.java, src/main/java/io/weaviate/client/v1/batch/api/ObjectsBatcher.java, src/main/java/io/weaviate/client/v1/batch/model/ObjectsGetResponseAO2Result.java, src/test/java/io/weaviate/integration/client/async/batch/ClientBatchGrpcCreateTest.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchCreateTest.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchGrpcCreateTest.java, src/test/java/io/weaviate/integration/tests/batch/BatchObjectsTestSuite.java
This PR aligns Java client with how Go client [treats partial errors in batch](https://github.com/weaviate/weaviate-go-client/blob/93535fb0af578a4d710dcddcdb63252fc8285fc2/weaviate/grpc/batch/batch.go#L324). 
I had to make a tradeoff between gRPC batching returning the same response as REST-batching and returning a response that's similar to the one `internalGrpc` returns now; I opted for the latter. Check [this comment](https://github.com/weaviate/java-client/pull/358/files?diff=unified&w=0#diff-d7c761d76ef9c877430249d277c9611f38b72819f95791c31808f6ee2238ed84R365-R372) for more details.
=> fix: return batch errors alongside successfully inserted objects

src/main/java/io/weaviate/client/v1/experimental/SearchClient.java, src/test/java/io/weaviate/integration/client/grpc/GRPCBenchTest.java
There is a [known JDK bug](https://bugs.openjdk.org/browse/JDK-8148463) which breaks unpacking the database response in case one of the collection properties is null.
Our mapping code also wasn't covering the case where the proto value is actual `null`. This PR fixes both issues.
=> fix(experimental): handle null property values

pom.xml
This patch includes a fix for a high severity vulnerability. For details see this Dependabot alert: https://github.com/weaviate/java-client/security/dependabot/4
=> chore: bump httpclient to 5.4.3

src/main/java/io/weaviate/client/v1/async/schema/Schema.java, src/main/java/io/weaviate/client/v1/async/schema/api/VectorAdder.java, src/main/java/io/weaviate/client/v1/schema/Schema.java, src/main/java/io/weaviate/client/v1/schema/api/VectorAdder.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/async/schema/ClientSchemaTest.java, src/test/java/io/weaviate/integration/client/schema/ClientSchemaTest.java
This PR adds a `client.schema().vectorAdder()` method, which lets users add named vectors in collections. The only pre-condition is that the collection must already define a named vector (during its creation).
Supported by both sync and async clients.
=> Adding named vectors to collections

src/it/java/io/weaviate/integration/SearchITest.java, src/main/java/io/weaviate/client6/v1/api/collections/WeaviateCollectionsClientAsync.java, src/main/java/io/weaviate/client6/v1/internal/rest/DefaultRestTransport.java
WeaviateCollectionsClientAsync should construct CollectionHandleAsync.
Also fixed a typo in DefaultRestTransport which was preventing deserialization of a perfectly valid return value.
=> v6: fix async toolchain

src/it/java/io/weaviate/integration/DataITest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/Reference.java, src/main/java/io/weaviate/client6/v1/api/collections/data/ReferenceAddRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/ReferenceDeleteRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/ReferenceReplaceRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/WeaviateDataClient.java
This PR adds 3 new methods to the `data` namespace:
```java
things.data.referenceAdd("from-uuid", "belongsTo", Reference.collection("Owners, "to-uuid"));
things.data.referenceReplace("from-uuid", "belongsTo", Reference.collection("Owners, "to-uuid"));
things.data.referenceDelete("from-uuid", "belongsTo", Reference.collection("Owners, "to-uuid"));
```
In the next PRs we will also add -Many counterparts to other data methods: insertMany, deleteMany, referencesAddMany.
=> v6: Add, replace, and delete object references

src/it/java/io/weaviate/integration/DataITest.java, src/main/java/io/weaviate/client6/v1/api/collections/CollectionHandle.java, src/main/java/io/weaviate/client6/v1/api/collections/CollectionHandleAsync.java, src/main/java/io/weaviate/client6/v1/api/collections/data/ReplaceObjectRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/UpdateObjectRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/WeaviateDataClient.java, src/main/java/io/weaviate/client6/v1/api/collections/data/WeaviateDataClientAsync.java
This PR adds `data.exists`, `data.update`, and `data.replace` methods.
=> v6: Add missing `data` methods

src/it/java/io/weaviate/integration/SearchITest.java, src/main/java/io/weaviate/client6/v1/api/collections/aggregate/AbstractAggregateClient.java, src/main/java/io/weaviate/client6/v1/api/collections/query/AbstractQueryClient.java, src/main/java/io/weaviate/client6/v1/api/collections/query/BaseQueryOptions.java, src/main/java/io/weaviate/client6/v1/api/collections/query/BaseVectorSearchBuilder.java, src/main/java/io/weaviate/client6/v1/api/collections/query/Bm25.java, src/main/java/io/weaviate/client6/v1/api/collections/query/ById.java, src/main/java/io/weaviate/client6/v1/api/collections/query/Hybrid.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearAudio.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearDepth.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearImu.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearMediaBuilder.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearObject.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearText.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearThermal.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearVector.java, src/main/java/io/weaviate/client6/v1/api/collections/query/NearVideo.java, src/main/java/io/weaviate/client6/v1/api/collections/query/SearchOperator.java, src/main/java/io/weaviate/client6/v1/api/collections/query/Where.java
This PR adds support for NearObject, Near<Media>, and Hybrid operators in `query` and `aggregate` namespaces.
```java
final var things = client.collections.use("Things");
things.query.hybrid("something like that", q -> q.alpha(0.3f).fusionType(Hybrid.FusionType.RANKED));
// .excludeSelf is a shorthand for `where(Where.uuid().ne("this-thing-id"))`
things.query.nearObject("this-thing-id", q -> q.excludeSelf());
```
There's also some minor improvements to Where-filter builders:
- `Where.uuid()` is a shorthand for `Where.property("_id")`
- `Where::toString` now prints human-readable representation of the filter
```java
Where.reference("hasFriend", "name").eq("Piglet")`
// Outputs:
//   "Where(hasFriend::name Equal Piglet)"
```
- Calls to `.where(...)` can now be chained -- individual …
=> v6: NearObject, Near<Media>, and Hybrid queries

src/it/java/io/weaviate/containers/Weaviate.java, src/it/java/io/weaviate/integration/CollectionsITest.java, src/it/java/io/weaviate/integration/ReferencesITest.java, src/main/java/io/weaviate/client6/v1/api/collections/CollectionConfig.java, src/main/java/io/weaviate/client6/v1/api/collections/CreateCollectionRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/Generative.java, src/main/java/io/weaviate/client6/v1/api/collections/GetConfigRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/InvertedIndex.java, src/main/java/io/weaviate/client6/v1/api/collections/ListCollectionRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/ListCollectionResponse.java, src/main/java/io/weaviate/client6/v1/api/collections/MultiTenancy.java, src/main/java/io/weaviate/client6/v1/api/collections/Property.java, src/main/java/io/weaviate/client6/v1/api/collections/ReferenceProperty.java, src/main/java/io/weaviate/client6/v1/api/collections/Replication.java, src/main/java/io/weaviate/client6/v1/api/collections/Reranker.java, src/main/java/io/weaviate/client6/v1/api/collections/Sharding.java, src/main/java/io/weaviate/client6/v1/api/collections/Vectorizer.java, src/main/java/io/weaviate/client6/v1/api/collections/WeaviateCollection.java, src/main/java/io/weaviate/client6/v1/api/collections/WeaviateCollectionsClient.java, src/main/java/io/weaviate/client6/v1/api/collections/WeaviateCollectionsClientAsync.java, src/main/java/io/weaviate/client6/v1/api/collections/config/UpdateCollectionRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/config/WeaviateConfigClient.java, src/main/java/io/weaviate/client6/v1/api/collections/config/WeaviateConfigClientAsync.java, src/main/java/io/weaviate/client6/v1/api/collections/generative/CohereGenerative.java, src/main/java/io/weaviate/client6/v1/api/collections/rerankers/CohereReranker.java, src/main/java/io/weaviate/client6/v1/internal/json/JSON.java, src/test/java/io/weaviate/client6/v1/internal/json/JSONTest.java
This PR extends collection / property configuration parameters and adds the ability for updating this configuration.
```java
final var things = client.collection.use("Things");
things.config.update(collection -> collection
.description("felt cute might delete later")
.invertedIndex(idx -> idx.cleanupIntervalSeconds(30)
.replication(repl -> repl.asyncEnabled(true))
.propertyDescription("name", "what the thing is called"));
```
[Implementation detail]: Internally this is enabled by 2 handy methods that both `Property` and `CollectionConfig` have: "edit".
```java
// Create config builder that has existing properties pre-filled.
var newConfigBuilder = oldConfig.edit();
newConfigBuilder.generativeModules(Generative.cohere());
// Creates a copy of the config object with changes applied.
var …
```
=> v6: Complete collection configuration and missing `config` functionality

src/it/java/io/weaviate/integration/CollectionsITest.java, src/main/java/io/weaviate/client6/v1/api/collections/config/GetShardsRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/config/Shard.java, src/main/java/io/weaviate/client6/v1/api/collections/config/ShardStatus.java, src/main/java/io/weaviate/client6/v1/api/collections/config/UpdateShardStatusRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/config/WeaviateConfigClient.java, src/main/java/io/weaviate/client6/v1/api/collections/config/WeaviateConfigClientAsync.java
```java
var things = client.collections.use("Things");
// List existing shards
var shards = things.config.getShards();
// Update status
var fullShards = new ArrayList<>();
for (var shard : shards) {
if (shard.name().contains("full") && !shard.status.equals("READONLY")) {
fullShards.add(shard.name());
}
}
things.config.updateShards(ShardStatus.READONLY, fullShards);
```
=> v6: Get and update shard status

src/main/java/io/weaviate/client/WeaviateClient.java, src/main/java/io/weaviate/client/base/AsyncBaseClient.java, src/main/java/io/weaviate/client/v1/aliases/Aliases.java, src/main/java/io/weaviate/client/v1/aliases/api/AliasAllGetter.java, src/main/java/io/weaviate/client/v1/aliases/api/AliasCreator.java, src/main/java/io/weaviate/client/v1/aliases/api/AliasDeleter.java, src/main/java/io/weaviate/client/v1/aliases/api/AliasGetter.java, src/main/java/io/weaviate/client/v1/aliases/api/AliasUpdater.java, src/main/java/io/weaviate/client/v1/aliases/model/Alias.java, src/main/java/io/weaviate/client/v1/async/WeaviateAsyncClient.java, src/main/java/io/weaviate/client/v1/async/aliases/Aliases.java, src/main/java/io/weaviate/client/v1/async/aliases/api/AliasAllGetter.java, src/main/java/io/weaviate/client/v1/async/aliases/api/AliasCreator.java, src/main/java/io/weaviate/client/v1/async/aliases/api/AliasDeleter.java, src/main/java/io/weaviate/client/v1/async/aliases/api/AliasGetter.java, src/main/java/io/weaviate/client/v1/async/aliases/api/AliasUpdater.java, src/main/java/io/weaviate/client/v1/rbac/api/WeaviatePermission.java, src/main/java/io/weaviate/client/v1/rbac/model/AliasPermission.java, src/main/java/io/weaviate/client/v1/rbac/model/AliasesPermission.java, src/main/java/io/weaviate/client/v1/rbac/model/Permission.java, src/test/java/io/weaviate/client/v1/rbac/api/WeaviatePermissionTest.java, src/test/java/io/weaviate/client/v1/rbac/model/PermissionTest.java, src/test/java/io/weaviate/integration/client/aliases/ClientAliasesTest.java, src/test/java/io/weaviate/integration/client/async/aliases/ClientAliasesTest.java, src/test/java/io/weaviate/integration/tests/rbac/ClientRbacTestSuite.java
This PR adds API for managing collection aliases and extends the set of permissions with `AliasesPermissions`.
```java
client.aliases().creator().withClassName("Pizza").withAlias("PizzaPie").run();
client.aliases().allGetter().run();
client.aliases().getter().withAlias("PizzaPie").run();
client.aliases().updater().withAlias("PizzaPie").withNewClassName("Langos").run();
client.aliases().deleter().withAlias("PizzaPie").run();
```
```java
.withPermissions(
Permission.aliases("PizzaPie", AliasesPermission.Action.CREATE, AliasesPermission.Action.DELETE)
); 
```
=> feat: Support collection aliases

pom.xml
‼️ org.apache.commons::commons-lang3 3.17.0 -> 3.18.0 prevents severe vulnerability: https://www.cve.org/CVERecord?id=CVE-2025-48924
Minor upgrades:
- io.grpc:grpc-protobuf 1.70.0 -> 1.71.0
- io.grpc:grpc-stub 1.68.2 -> 1.70.0
- io.grpc:grpc-netty-shaded 1.68.2 -> 1.70.0
- com.google.protobuf:protobuf-java(-util) 4.29.3 -> 4.30.0
- and more: https://github.com/weaviate/java-client/pull/413/commits/4e1823893aeddc774f4ecedeaa0f4fd049d6c02a, https://github.com/weaviate/java-client/pull/413/commits/2f08434a6d21198295ed124195f78c6bd61816ce
Supersedes these PRs: #359, #360, #365, #366, #367, #411, #412
=> 🔒 chore(security): upgrade dependencies

src/it/java/io/weaviate/integration/AggregationITest.java, src/main/java/io/weaviate/client6/v1/api/collections/aggregate/GroupBy.java
Previously our Aggregate API was only exposing `objectLimit`, which is relevant for the filter-query, e.g. NearVector or Hybrid.
`limit`, on the other hand, is only relevant to grouped queries, so we push it to GroupBy options.
=> v6: Add `limit` to GroupBy parameter in Aggregate queries

src/main/java/io/weaviate/client/v1/rbac/model/AliasPermission.java, src/main/java/io/weaviate/client/v1/rbac/model/Permission.java, src/test/java/io/weaviate/client/v1/rbac/api/WeaviatePermissionTest.java, src/test/java/io/weaviate/client/v1/rbac/model/PermissionTest.java, src/test/java/io/weaviate/integration/tests/rbac/ClientRbacTestSuite.java
Follow-up to #409: accept `collection` parameter for AliasPermission ([reference Python PR](https://github.com/weaviate/weaviate-python-client/pull/1734)).
=> Configure alias permissions per collection

src/main/java/io/weaviate/client/v1/async/backup/api/BackupRestorer.java, src/main/java/io/weaviate/client/v1/backup/api/BackupRestorer.java, src/main/java/io/weaviate/client/v1/backup/model/RbacRestoreOption.java, src/test/java/io/weaviate/integration/client/WeaviateDockerCompose.java, src/test/java/io/weaviate/integration/client/WeaviateDockerComposeBackup.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/async/backup/ClientBackupTest.java, src/test/java/io/weaviate/integration/client/backup/ClientBackupTest.java, src/test/java/io/weaviate/integration/tests/backup/BackupTestSuite.java
Reference Python PR: https://github.com/weaviate/weaviate-python-client/pull/1737
=> Add backup restore options for users and roles

src/main/java/io/weaviate/client6/v1/api/collections/CollectionConfig.java, src/test/java/io/weaviate/client6/v1/internal/json/JSONTest.java
If a collection has no properties, trying to read `"properties"` as JSON array will produce a NPE. This PR adds additional checks to that part of the code.
=> fix(v6): add defensive checks to JSON deserialization

README.md, pom.xml
Resolves #422 
Trying to `java -jar` a fat JAR built with something like `maven-assembly-plugin` users will see this error as soon as they try to instantiate WeaviateClient:
```sh
Exception in thread "main" java.lang.IllegalArgumentException: Address types of NameResolver 'unix' for 'grpc-
blahblahblah.gcp.weaviate.cloud:443' not supported by transport
at io.grpc.internal.ManagedChannelImplBuilder.getNameResolverProvider(ManagedChannelImplBuilder.java:8
50)
at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:700)
at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:272)
at io.weaviate.client6.v1.internal.grpc.DefaultGrpcTransport.buildChannel(DefaultGrpcTransport.java:92
)
at io.weaviate.client6.v1.internal.grpc.DefaultGrpcTransport.<init …
```
=> v6: include a shaded version of client6 in deployment bundle

src/it/java/io/weaviate/integration/AggregationITest.java, src/it/java/io/weaviate/integration/CollectionsITest.java, src/it/java/io/weaviate/integration/DataITest.java, src/it/java/io/weaviate/integration/SearchITest.java, src/main/java/io/weaviate/client6/v1/api/collections/ObjectMetadata.java, src/main/java/io/weaviate/client6/v1/api/collections/Vectorizer.java, src/main/java/io/weaviate/client6/v1/api/collections/Vectorizers.java, src/main/java/io/weaviate/client6/v1/api/collections/Vectors.java, src/main/java/io/weaviate/client6/v1/api/collections/data/InsertObjectRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/ReplaceObjectRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/data/UpdateObjectRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/query/QueryRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/vectorizers/Img2VecNeuralVectorizer.java, src/main/java/io/weaviate/client6/v1/api/collections/vectorizers/Multi2VecClipVectorizer.java, src/main/java/io/weaviate/client6/v1/api/collections/vectorizers/SelfProvidedVectorizer.java, src/main/java/io/weaviate/client6/v1/api/collections/vectorizers/Text2VecContextionaryVectorizer.java, src/main/java/io/weaviate/client6/v1/api/collections/vectorizers/Text2VecWeaviateVectorizer.java, src/test/java/io/weaviate/client6/v1/internal/json/JSONTest.java
It should now be possible to declare properties to include in `text2vec-weaviate` and `text2vec-contextionary` vectors.
```java
.vectors(
Vectorizers.text2vecWeaviate(t2v -> t2v.sourceProperties("firstName", "lastName"));
Vectorizers.text2vecContextionary(t2v -> t2v.sourceProperties("middleName", "patronymic")));
```
Secondly, the syntax for adding several vectors to an object does not include a tucked-builder pattern anymore, making it similar to how vector indices are configured (see above).
```java
.vectors(
Vectors.of("1d", new float[]{...}),
Vectors.of("2d", new float[][]{...}));
```
Also wrote Javadoc for methods and classes related to vectors/vectorizers.
=> v6: Add `sourceProperties` to text-based vectorizers

src/main/java/io/weaviate/client6/v1/api/collections/Vectors.java, src/main/java/io/weaviate/client6/v1/api/collections/aggregate/AggregateRequest.java, src/main/java/io/weaviate/client6/v1/api/collections/pagination/AsyncPage.java, src/main/java/io/weaviate/client6/v1/api/collections/pagination/CursorSpliterator.java, src/main/java/io/weaviate/client6/v1/api/collections/query/QueryRequest.java, src/main/java/io/weaviate/client6/v1/internal/orm/PojoDescriptor.java, src/main/java/io/weaviate/client6/v1/internal/orm/PojoReader.java
Assertions should enforce invariants, not signal error conditions. Unlike Exceptions, AssertionErrors are not caught by catch (Exception e) and may be more unpredictable.
We should try to only ever use assertions for cases that can never happen unless there's been a programming mistake on our side.
Everything else, e.g. server responses, network errors, client's input (ORM) should be dealt with via exceptions.
=> v6: Assertions
