src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearObjectArgument.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearTextArgument.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/ExploreBuilder.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilder.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearObjectArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearTextArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/ExploreBuilderTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java
=> gh-25 Improve builders

src/main/java/technology/semi/weaviate/client/base/Client.java, src/main/java/technology/semi/weaviate/client/base/Result.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Aggregate.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Explore.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Get.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java
=> gh-28 Add result implementation to graphql package

pom.xml, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/ExploreBuilder.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilder.java
=> gh-29 Adjust pom.xml for release

pom.xml, src/main/java/technology/semi/weaviate/client/base/BaseClient.java, src/main/java/technology/semi/weaviate/client/base/http/HttpClient.java, src/main/java/technology/semi/weaviate/client/base/http/HttpResponse.java, src/main/java/technology/semi/weaviate/client/base/http/impl/CommonsHttpClientImpl.java, src/main/java/technology/semi/weaviate/client/v1/schema/model/Class.java, src/main/java/technology/semi/weaviate/client/v1/schema/model/Property.java, src/main/java/technology/semi/weaviate/client/v1/schema/model/Schema.java, src/test/java/technology/semi/weaviate/integration/client/contextionary/ClientContextionaryTest.java
=> gh-11 Fix contextionary extensions creator

src/main/java/technology/semi/weaviate/client/v1/batch/api/ObjectsBatcher.java, src/main/java/technology/semi/weaviate/client/v1/batch/model/ObjectGetResponse.java, src/main/java/technology/semi/weaviate/client/v1/batch/model/ObjectsBatchRequestBody.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectCreator.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectUpdater.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectValidator.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectsGetter.java, src/main/java/technology/semi/weaviate/client/v1/data/model/Deprecation.java, src/main/java/technology/semi/weaviate/client/v1/data/model/MultipleRef.java, src/main/java/technology/semi/weaviate/client/v1/data/model/ObjectsListResponse.java, src/main/java/technology/semi/weaviate/client/v1/data/model/ReferenceMetaClassification.java, src/main/java/technology/semi/weaviate/client/v1/data/model/SingleRef.java, src/main/java/technology/semi/weaviate/client/v1/data/model/WeaviateObject.java, src/main/java/technology/semi/weaviate/client/v1/schema/api/ClassCreator.java, src/main/java/technology/semi/weaviate/client/v1/schema/api/SchemaDeleter.java, src/main/java/technology/semi/weaviate/client/v1/schema/model/Schema.java, src/main/java/technology/semi/weaviate/client/v1/schema/model/WeaviateClass.java, src/test/java/technology/semi/weaviate/client/v1/data/model/ObjectTest.java, src/test/java/technology/semi/weaviate/integration/client/WeaviateTestGenerics.java, src/test/java/technology/semi/weaviate/integration/client/batch/ClientBatchTest.java, src/test/java/technology/semi/weaviate/integration/client/classifications/ClientClassificationsTest.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java
=> gh-34 Rename weaviate Object / Class class to WeaviateObject / WeaviateClass

README.md, src/main/java/technology/semi/weaviate/client/Config.java, src/main/java/technology/semi/weaviate/client/WeaviateClient.java, src/test/java/technology/semi/weaviate/integration/client/batch/ClientBatchTest.java, src/test/java/technology/semi/weaviate/integration/client/classifications/ClientClassificationsTest.java, src/test/java/technology/semi/weaviate/integration/client/contextionary/ClientContextionaryTest.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java
=> gh-37 Update config and weaviate client

src/main/java/technology/semi/weaviate/client/Config.java, src/main/java/technology/semi/weaviate/client/base/BaseClient.java, src/main/java/technology/semi/weaviate/client/base/http/impl/CommonsHttpClientImpl.java, src/main/java/technology/semi/weaviate/client/v1/batch/Batch.java, src/main/java/technology/semi/weaviate/client/v1/classifications/Classifications.java, src/main/java/technology/semi/weaviate/client/v1/contextionary/Contextionary.java, src/main/java/technology/semi/weaviate/client/v1/data/Data.java, src/main/java/technology/semi/weaviate/client/v1/misc/Misc.java, src/main/java/technology/semi/weaviate/client/v1/schema/Schema.java
=> gh-39 Add support for connections which require auth token

src/main/java/technology/semi/weaviate/client/v1/graphql/GraphQL.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java
=> gh-41 Make graphQL arguments discoverable

.travis.yml
=> gh-44 Prepare for 1.0.0 release

pom.xml, src/main/java/technology/semi/weaviate/client/base/BaseClient.java, src/main/java/technology/semi/weaviate/client/base/http/HttpClient.java, src/main/java/technology/semi/weaviate/client/base/http/impl/CommonsHttpClientImpl.java, src/main/java/technology/semi/weaviate/client/v1/data/Data.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectCreator.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectDeleter.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectUpdater.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectValidator.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ReferenceCreator.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ReferenceDeleter.java, src/main/java/technology/semi/weaviate/client/v1/data/api/ReferenceReplacer.java, src/main/java/technology/semi/weaviate/client/v1/data/builder/ReferencePayloadBuilder.java, src/main/java/technology/semi/weaviate/client/v1/data/model/SingleRef.java, src/main/java/technology/semi/weaviate/client/v1/schema/api/ClassDeleter.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientReferencesTest.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java
=> gh-46 Add reference builder

.travis.yml, pom.xml
=> gh-50 Fix maven deployment process

src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/AskArgument.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearTextArgument.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/AskArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearTextArgumentTest.java
=> gh-56 Add support for spellcheck module

src/main/java/technology/semi/weaviate/client/base/BaseClient.java, src/main/java/technology/semi/weaviate/client/base/Serializer.java, src/main/java/technology/semi/weaviate/client/base/http/impl/CommonsHttpClientImpl.java, src/test/java/technology/semi/weaviate/client/base/SerializerTest.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/resources/docker-compose-test.yaml
=> gh-60 Umlaute ("äöü" etc.) don't get sent correctly to weaviate

src/main/java/technology/semi/weaviate/client/v1/schema/model/DataType.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java
=> gh-62 Add support for array data types

src/main/java/technology/semi/weaviate/client/v1/schema/model/DataType.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java, src/test/resources/docker-compose-test.yaml
Changes made:
- added support for additional array types
Closes #65
=> gh-65 Add support for boolean[] and date[] data types

src/main/java/technology/semi/weaviate/client/v1/graphql/query/Aggregate.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Explore.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Get.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/GeoCoordinatesParameter.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/GroupArgument.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/GroupType.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/Parameter.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/WhereArgument.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/WhereFilter.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/WhereOperator.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/AggregateBuilder.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilder.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/fields/Field.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/fields/Fields.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/GeoCoordinatesParameterTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/GroupArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/WhereArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/AggregateBuilderTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/ExploreBuilderTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/fields/FieldTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/fields/FieldsTest.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java
=> gh-64 Introducing some builder-functionality to weaviate's Java client for building where- and field-clauses

pom.xml
=> gh-68 Update project libraries

src/main/java/technology/semi/weaviate/client/v1/graphql/query/Get.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilder.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java
Changes made:
- added suuport for offset param
Closes #70
=> gh-70 Add support for offset param

src/main/java/technology/semi/weaviate/client/v1/data/api/ObjectCreator.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/resources/docker-compose-test.yaml
=> gh-72 Creating a data object with custom vectors

src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/AskArgument.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/AskArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/resources/docker-compose-test.yaml
=> gh-74 Add support for rerank parameter in ask argument

src/main/java/technology/semi/weaviate/client/base/BaseClient.java, src/main/java/technology/semi/weaviate/client/base/http/HttpClient.java, src/main/java/technology/semi/weaviate/client/base/http/impl/CommonsHttpClientImpl.java, src/main/java/technology/semi/weaviate/client/v1/data/Data.java, src/main/java/technology/semi/weaviate/client/v1/schema/api/ObjectsChecker.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java
=> gh-76 Add support for object check request

src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java
=> gh-78 Enhance object check tests

src/main/java/technology/semi/weaviate/client/v1/graphql/GraphQL.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/resources/docker-compose-test.yaml
=> gh-80 Add graphql test for group filter

src/main/java/technology/semi/weaviate/client/v1/data/model/ObjectReference.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/fields/Field.java, src/test/java/technology/semi/weaviate/client/v1/data/model/ObjectTest.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientReferencesTest.java
=> gh-82 Reference property doesn't get serialised to Json

src/main/java/technology/semi/weaviate/client/base/Result.java, src/main/java/technology/semi/weaviate/client/base/WeaviateErrorResponse.java, src/test/java/technology/semi/weaviate/client/base/SerializerTest.java, src/test/java/technology/semi/weaviate/client/v1/data/model/ObjectTest.java, src/test/java/technology/semi/weaviate/integration/client/data/ClientDataTest.java
=> gh-84 Fix response error parsing logic

src/main/java/technology/semi/weaviate/client/v1/schema/Schema.java, src/main/java/technology/semi/weaviate/client/v1/schema/api/ClassGetter.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java
=> gh-86 Add support for /v1/schema/{className}

src/main/java/technology/semi/weaviate/client/v1/graphql/query/Aggregate.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/AggregateBuilder.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/AggregateBuilderTest.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java
=> gh-87 Add support for where argument in Aggregate

src/main/java/technology/semi/weaviate/client/v1/schema/model/Property.java, src/main/java/technology/semi/weaviate/client/v1/schema/model/Tokenization.java, src/test/java/technology/semi/weaviate/integration/client/WeaviateTestGenerics.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/java/technology/semi/weaviate/integration/client/schema/ClientSchemaTest.java, src/test/resources/docker-compose-test.yaml
To be merged after weaviate release.
Proper weaviate version to be set before merging.
`testGraphQLGetWithWhereByFieldTokenizedProperty` test to be improved / fixed after weaviate fix for stopwords search
=> gh-1821 index full string field

pom.xml, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Aggregate.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/Get.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearVectorArgument.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/AggregateBuilder.java, src/main/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilder.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/argument/NearVectorArgumentTest.java, src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java, src/test/java/technology/semi/weaviate/integration/client/graphql/ClientGraphQLTest.java, src/test/java/technology/semi/weaviate/integration/client/misc/ClientMiscTest.java, src/test/resources/docker-compose-test.yaml
Set to draft state for review -- after review we should introduce the `NearVectorArgument` builder in a new version, as it is a breaking change.
Update 4/18/21
Breaking changes have been added, we will release the changes under a new version using git tags/Nexus
=> Implement nearMedia filters for agg query

CODE_OF_CONDUCT.md, CONTRIBUTE.md, README.md, pom.xml, tools/prepare_release.sh
This PR adds a `./tools/prepare_release.sh` script in order to unify and automate the release process.
Example usage: `./tools/prepare_release.sh 3.2.0`
=> Add prepare release script

src/test/java/technology/semi/weaviate/client/v1/graphql/query/builder/ExploreBuilderTest.java
Test was duplicating a check for certainty
=> Fix test to check for correct serialisation of distance argument

src/main/java/technology/semi/weaviate/client/v1/batch/model/ObjectGetResponse.java, src/main/java/technology/semi/weaviate/client/v1/data/model/WeaviateObject.java
fixes https://github.com/semi-technologies/weaviate-java-client/issues/144
=> Removes @SuperBuilder and copies fields from WeaviateObject to ObjectGetResponse

src/test/java/technology/semi/weaviate/integration/client/batch/ClientBatchCreateTest.java
I'm trying to add an example for partial batch error but seem unable to get a classnotfound error. This PR demonstrates that by adding an integration test. Related to #150
=> Add test for partial batch error

src/main/java/io/weaviate/client/v1/graphql/GraphQL.java, src/main/java/io/weaviate/client/v1/graphql/query/Aggregate.java, src/main/java/io/weaviate/client/v1/graphql/query/Explore.java, src/main/java/io/weaviate/client/v1/graphql/query/Get.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearAudioArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearDepthArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearImuArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearMediaArgumentHelper.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearThermalArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/argument/NearVideoArgument.java, src/main/java/io/weaviate/client/v1/graphql/query/builder/AggregateBuilder.java, src/main/java/io/weaviate/client/v1/graphql/query/builder/ExploreBuilder.java, src/main/java/io/weaviate/client/v1/graphql/query/builder/GetBuilder.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearAudioArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearDepthArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearImageArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearImuArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearMediaArgumentHelperTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearThermalArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/argument/NearVideoArgumentTest.java, src/test/java/io/weaviate/client/v1/graphql/query/builder/AggregateBuilderTest.java, src/test/java/io/weaviate/client/v1/graphql/query/builder/ExploreBuilderTest.java, src/test/java/io/weaviate/client/v1/graphql/query/builder/GetBuilderTest.java
adds support for `nearVideo`, `nearAudio`, `nearDepth`, `nearThermal`, `nearIMU`
=> Adds near<media> support

src/main/java/io/weaviate/client/base/util/CrossReference.java, src/main/java/io/weaviate/client/v1/batch/grpc/BatchObjectConverter.java, src/test/java/io/weaviate/client/base/util/CrossReferenceTest.java, src/test/java/io/weaviate/integration/client/WeaviateTestGenerics.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchGrpcCreateTest.java, src/test/resources/docker-compose-azure.yaml, src/test/resources/docker-compose-cluster.yaml, src/test/resources/docker-compose-okta-cc.yaml, src/test/resources/docker-compose-okta-users.yaml, src/test/resources/docker-compose-proxy.yaml, src/test/resources/docker-compose-test.yaml, src/test/resources/docker-compose-wcs.yaml
This PR adds tests for gRPC Batch API to ensure that it works also good with cross references (single and multi cross references).
=> Add support for cross references in gRPC Batch API

src/main/java/io/weaviate/client/WeaviateClient.java, src/main/java/io/weaviate/client/base/grpc/GrpcClient.java, src/main/java/io/weaviate/client/v1/batch/Batch.java, src/main/java/io/weaviate/client/v1/batch/api/ObjectsBatcher.java, src/test/java/io/weaviate/integration/client/auth/AuthWCSUsersApiKeyTest.java
This PR fixes gRPC authorization.
=> Add gRPC authorization suppport

src/main/java/io/weaviate/client/v1/misc/model/SQConfig.java, src/main/java/io/weaviate/client/v1/misc/model/VectorIndexConfig.java, src/test/java/io/weaviate/integration/client/batch/ClientBatchGrpcCreateTest.java
This PR adds support for SQ vector index type
=> Add support for HNSW SQ vector index type

src/main/java/io/weaviate/client/v1/misc/model/ReplicationConfig.java, src/test/java/io/weaviate/integration/client/schema/ClusterSchemaTest.java
Adds support for asyncEnabled replication setting
=> Add support for asyncEnabled replication setting

src/main/java/io/weaviate/client/Config.java, src/main/java/io/weaviate/client/WeaviateAuthClient.java, src/test/java/io/weaviate/integration/client/auth/AuthWeaviateEmbeddingHeadersTest.java
Set `X-Weaviate-Api-Key` and `X-Weaviate-Cluster-URL` headers if the client is using `ApiKey` token provider.
=> Set authentication headers for Weaviate Embeddings service

src/main/java/io/weaviate/client/v1/misc/model/MultiVectorConfig.java, src/main/java/io/weaviate/client/v1/misc/model/MuveraConfig.java, src/test/java/io/weaviate/integration/client/WeaviateVersion.java, src/test/java/io/weaviate/integration/client/async/data/ClientDataTest.java, src/test/java/io/weaviate/integration/client/async/schema/ClientSchemaTest.java, src/test/java/io/weaviate/integration/client/data/ClientDataTest.java, src/test/java/io/weaviate/integration/client/schema/ClientSchemaTest.java
This PR allows users to enable muvera and configure the corresponding parameters which are:
- `ksim`: number of gaussian vectors for space partitioning, the number of cluster will be 2^ksim
- `dprojections`: projection dimensionality of each cluster vectors
- `repetitions`: number of times we repeat the space partitioning + dim projections for better approximation
=> Add muvera config
